# Generated by Django 4.1 on 2023-11-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('lanzamiento', models.PositiveIntegerField()),
                ('duracion', models.CharField(max_length=255)),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
